units_of_interest = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Barbuda',
    'Antigua',
    'Argentina',
    'Armenia',
    # 'Coral Sea Islands',
    'Australia',
    # 'Heard Island and McDonald Islands',
    # 'Christmas Island',
    # 'Cocos (Keeling) Islands',
    # 'Norfolk Island',
    # 'Ashmore and Cartier Islands',
    'Austria',
    'Azerbaijan',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Walloon Region',  # Union with Flemish Region to get Belgium
    'Flemish Region',
    'Brussels Capital Region',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',  # Union with the next two
    'Brcko District',
    'Republic Srpska',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'Macao S.A.R',
    'China',
    'Hong Kong S.A.R.',
    'Colombia',
    'Comoros',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Cyprus No Mans Area',  # Roll into Cyprus
    'Czechia',
    'Democratic Republic of the Congo',
    'Denmark',
    'Greenland',
    'Faroe Islands',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'East Timor',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Ethiopia',
    'Federated States of Micronesia',
    'Fiji',
    'Aland',  # Roll into Finland
    'Finland',
    'Reunion',
    'Martinique',
    # 'French Southern and Antarctic Lands',
    'Guadeloupe',
    'Clipperton Island',
    'French Guiana',
    'Wallis and Futuna',
    'Saint Martin',
    'Saint Barthelemy',
    'France',
    'New Caledonia',
    'Mayotte',
    'Saint Pierre and Miquelon',
    'French Polynesia',
    'Gabon',
    'Gambia',
    'Ajaria',  # Roll into Georgia
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Iraqi Kurdistan', # Roll into Iraq
    'Ireland',
    'Israel',
    'Gaza',  # Roll into Israel
    'West Bank',  # Roll into Israel
    'Italy',
    'Ivory Coast',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Baykonur Cosmodrome',  # Roll into Kazakhstan
    'Kenya',
    'Kiribati',
    'Kosovo',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Curaçao',
    'Aruba',
    'Netherlands',
    'Sint Maarten',
    'Caribbean Netherlands',
    'New Zealand',  # Keep dependencies autonomous
    'Cook Islands',
    'Tokelau',
    'Niue',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Korea',
    'Korean Demilitarized Zone (north)',  # Roll into NK
    'North Macedonia',
    'Northern Cyprus',  # Roll into Cyprus
    'Svalbard',  # Roll into Norway
    'Norway',
    'Bouvet Island',  # Roll into Norway
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Bougainville',  # Roll into PNG
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Madeira',
    'Azores',
    'Qatar',
    'Serbia',
    'Vojvodina',  # Roll into Serbia
    'Republic of the Congo',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Saudi Arabia',
    'Senegal',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'Puntland',  # Roll into Somalia
    'Somaliland',  # Roll into Somalia
    'South Africa',
    'South Korea',
    'Korean Demilitarized Zone (south)',  # Roll into SK
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'UNDOF',  # Roll into Syria
    'São Tomé and Principe',
    'Taiwan',
    'Tajikistan',
    'Thailand',
    'The Bahamas',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'South Georgia and the Islands',
    'Isle of Man',
    'Falkland Islands',
    'Saint Helena',
    'Guernsey',
    'Jersey',
    'Wales',
    'Montserrat',
    'Gibraltar',
    'Scotland',
    'England',
    'Turks and Caicos Islands',
    'British Indian Ocean Territory',
    'Cayman Islands',
    'British Virgin Islands',
    'Akrotiri Sovereign Base Area',
    'Bermuda',
    'Pitcairn Islands',
    'Northern Ireland',
    'Dhekelia Sovereign Base Area',
    'Anguilla',
    'Zanzibar',  # Roll into Tanzania
    'Tanzania',
    # 'Midway Islands',
    # 'Wake Atoll',
    # 'Palmyra Atoll',
    # 'Navassa Island',
    # 'Kingman Reef',
    'United States of America',
    # 'Johnston Atoll',
    # 'Baker Island',
    # 'Jarvis Island',
    'Northern Mariana Islands',
    'Guam',
    'United States Virgin Islands',
    'American Samoa',
    # 'Howland Island',
    'Puerto Rico',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican',
    'Venezuela',
    'Vietnam',
    'Western Sahara',
    'Yemen',
    'Zambia',
    'Zimbabwe',
    'eSwatini'
]

units_by_country = {
    'Belgium': ['Walloon Region', 'Flemish Region', 'Brussels Capital Region'],
    'Bosnia and Herzegovina': ['Bosnia and Herzegovina', 'Brcko District', 'Republic Srpska'],
    'Cyprus': ['Cyprus', 'Cyprus No Mans Area', 'Northern Cyprus'],
    'Finland': ['Aland', 'Finland'],
    'Georgia': ['Ajaria', 'Georgia'],
    'Iraq': ['Iraq', 'Iraqi Kurdistan'],
    'Israel': ['Israel', 'Gaza', 'West Bank'],
    'Kazakhstan': ['Kazakhstan', 'Baykonur Cosmodrome'],
    'North Korea': ['North Korea', 'Korean Demilitarized Zone (north)'],
    'Norway': ['Svalbard', 'Norway', 'Bouvet Island'],
    'Papua New Guinea': ['Bougainville', 'Papua New Guinea'],
    'Serbia': ['Serbia', 'Vojvodina'],
    'Somalia': ['Somalia', 'Puntland', 'Somaliland'],
    'South Korea': ['South Korea', 'Korean Demilitarized Zone (south)'],
    'Syria': ['Syria', 'UNDOF'],
    'Tanzania': ['Zanzibar', 'Tanzania']
}


def keep_unit(unit_name):
    return unit_name in units_of_interest


def get_unit_group(unit_name):
    if unit_name not in units_of_interest:
        return 'N/A'

    for country_name in units_by_country.keys():
        if unit_name in units_by_country[country_name]:
            return country_name

    return unit_name

